"""
This type stub file was generated by pyright.
"""

from .clients import AsyncpgClient, PsycopgClient, get_client, get_default_client
from .config import PGliteConfig
from .manager import PGliteManager

"""py-pglite: Python testing library for PGlite integration.

Provides seamless integration between PGlite (in-memory PostgreSQL)
and Python test suites with support for SQLAlchemy, SQLModel, and Django.
"""
__version__ = ...
__all__ = ["PGliteConfig", "PGliteManager", "get_client", "get_default_client", "PsycopgClient", "AsyncpgClient"]
