"""
This type stub file was generated by pyright.
"""

"""Extension management for py-pglite.

This module provides a registry of supported PGlite extensions and the
necessary JavaScript import details for each.
"""
SUPPORTED_EXTENSIONS: dict[str, dict[str, str]] = ...
