---
# paths:  # list or string
#   - docstr_coverage
# badge: docs  # Path
# exclude: .*/test  # regex
# verbose: 3  # int (0-4)
# skip_magic: True  # Boolean
# skip_file_doc: True  # Boolean
# skip_init: True  # Boolean
# skip_class_def: True  # Boolean
# skip_private: True  # Boolean
# follow_links: True  # Boolean
# accept_empty: True  # Boolean
# ignore_names_file: .*/test  # regex
# fail_under: 90  # int
# percentage_only: True  # Boolean
# ignore_patterns:  # Dict with key/value pairs of file-pattern/node-pattern
#   .*: method_to_ignore_in_all_files
#   FileWhereWeWantToIgnoreAllSpecialMethods: "__.+__"
#   SomeFile:
#     - method_to_ignore1
#     - method_to_ignore2
#     - method_to_ignore3
#   a_very_important_view_file:
#     - "^get$"
#     - "^set$"
#     - "^post$"
#   detect_.*:
#     - "get_val.*"
exclude: (?:(?:^|.*/)(?:\.venv|examples|\.archive|typings|tests|\.kiro|\.audit)(?:/|$))|(?:(?:^|.*/)src/tux/database/migrations(?:/versions)?(?:/|$))|(?:(?:^|.*/)migrations(?:/|$))
