---
# ==============================================================================
# TUX DISCORD BOT - UNIFIED CODECOV CONFIGURATION
# ==============================================================================
#
# This configuration is optimized for unified test coverage where all tests
# (unit, integration, e2e) run together and generate a single comprehensive
# coverage report.
#
# DOCUMENTATION: https://docs.codecov.com/docs/codecov-yaml
# ==============================================================================
# ==============================================================================
# CODECOV BEHAVIOR SETTINGS
# ==============================================================================
codecov:
  require_ci_to_pass: true
  # yamllint disable-line rule:truthy
  max_report_age: false
  disable_default_path_fixes: false
# ==============================================================================
# COVERAGE REQUIREMENTS
# ==============================================================================
coverage:
  precision: 2
  round: down
  range: 70...100
  status:
    project:
      # Overall project coverage - enforced at 80%
      default:
        target: 80%
        threshold: 1%
        informational: false  # Enforce coverage requirements

      # Component-specific coverage requirements (more lenient for complex areas)
      database:
        target: 85%
        threshold: 2%
        informational: false
        flags: [database]
      core:
        target: 80%
        threshold: 2%
        informational: false
        flags: [core]
      ui:
        target: 70%
        threshold: 3%
        informational: true  # UI components can be more lenient
        flags: [ui]
      modules:
        target: 75%
        threshold: 3%
        informational: true  # Command modules vary in complexity
        flags: [modules]
      services:
        target: 75%
        threshold: 3%
        informational: true  # Services may have external dependencies
        flags: [services]
    patch:
      # New code coverage requirements
      default:
        target: 80%
        threshold: 5%
        informational: false
        only_pulls: true
# ==============================================================================
# COMPONENT FLAG DEFINITIONS
# ==============================================================================
# Component-based flags for tracking coverage by architectural areas.
# These automatically categorize coverage based on file paths, providing
# better insights than test-type categorization.
flags:
  database:
    paths: [src/tux/database/]
    carryforward: true
  core:
    paths: [src/tux/core/]
    carryforward: true
  ui:
    paths: [src/tux/ui/]
    carryforward: true
  modules:
    paths: [src/tux/modules/]
    carryforward: true
  services:
    paths: [src/tux/services/]
    carryforward: true
# ==============================================================================
# FILE IGNORING
# ==============================================================================
ignore:
  # Test files and development artifacts
  - tests/
  - conftest.py
  - .pytest_cache/
  - .ruff_cache/
  - htmlcov/

  # Build and environment files
  - .venv/
  - typings/
  - __pycache__/

  # Project management files
  - docs/
  - scripts/
  - assets/
  - logs/
  - '*.md'
  - '*.toml'
  - '*.lock'
  - '*.nix'
  - flake.*
  - shell.nix

  # Generated files
  - prisma/
# ==============================================================================
# PARSER CONFIGURATION
# ==============================================================================
parsers:
  v1:
    include_full_missed_files: true
# ==============================================================================
# COMMENT CONFIGURATION
# ==============================================================================
comment:
  layout: condensed_header, diff, flags, components, condensed_files, condensed_footer
  behavior: default
  require_changes: true
  require_base: false
  require_head: true
  after_n_builds: 1
  show_carryforward_flags: true
# ==============================================================================
# GITHUB INTEGRATION
# ==============================================================================
# Enhanced integration with GitHub's pull request interface
github_checks:
  annotations: true  # Show line-by-line coverage in PR file diffs
# ==============================================================================
# PATH NORMALIZATION
# ==============================================================================
# Fix coverage.py path mapping for src/tux structure
fixes: [.*/src/tux/::src/tux/, src/tux/::src/tux/]
