services:
  tux-postgres-dev:
    container_name: tux-postgres-dev
    hostname: tux-postgres-dev
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: tuxdb
      POSTGRES_USER: tuxuser
      POSTGRES_PASSWORD: tuxpass
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - 5433:5432
    volumes:
      - tux_dev_postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U tuxuser -d tuxdb
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  tux-dev:
    container_name: tux-dev
    hostname: tux-dev
    image: tux:${TUX_IMAGE_TAG:-dev}
    build:
      context: .
      args:
        VERSION: ${VERSION}
        GIT_SHA: ${GIT_SHA}
        BUILD_DATE: ${BUILD_DATE}
      dockerfile: Dockerfile
      target: dev
    command:
      - sh
      - -c
      - exec uv run tux --dev start
    depends_on:
      tux-postgres-dev:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: .
          target: /app/
          ignore:
            - .cache/
            - .idea/
            - .venv/
            - .vscode/
            - '**/__pycache__/'
            - '**/*.pyc'
            - '*.log'
            - .*.swp
            - '*~'
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: uv.lock
        - action: rebuild
          path: src/tux/database/migrations/
    volumes:
      - tux_dev_cache:/app/.cache
      - tux_dev_temp:/app/temp
      - tux_dev_user_home:/home/nonroot
    env_file:
      - .env
    environment:
      TUX_VERSION: ${VERSION}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '1.0'
        reservations:
          memory: 512m
          cpus: '0.5'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
volumes:
  tux_dev_cache:
    driver: local
  tux_dev_temp:
    driver: local
  tux_dev_user_home:
    driver: local
  tux_dev_postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/postgres
