---

# NOTE: This file is used for local development purposes only.

services:
  tux:
    container_name: tux-dev
    image: tux:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    develop:
      watch:
        - action: sync
          path: .
          target: /app/
          ignore:
            - .cache/
            - .git/
            - .idea/
            - .venv/
            - .vscode/
            - "**/__pycache__/"
            - "**/*.pyc"
            - "*.log"
            - "*.swp"
            - ".*.swp"
            - "*~"
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: poetry.lock
        - action: rebuild
          path: prisma/schema/
    volumes:
      - tux_dev_cache:/app/.cache
      - tux_dev_temp:/app/temp
    env_file:
      - path: .env
        required: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  tux_dev_cache:
    driver: local
  tux_dev_temp:
    driver: local
