"""
Fact Plugin for Tux Bot.

This plugin provides random fact generation with configurable fact types,
placeholder substitution, and automated fact posting functionality.
Facts are loaded from TOML files and support various categories.
"""

import contextlib
import random
import tomllib
from pathlib import Path
from typing import Any

import discord
from discord import app_commands
from discord.ext import commands
from loguru import logger

from tux.core.base_cog import BaseCog
from tux.core.bot import Tux
from tux.services.http_client import http_client
from tux.shared.config import CONFIG
from tux.shared.version import get_version
from tux.ui.embeds import EmbedCreator

# Define workspace root relative to the project root
workspace_root = Path(__file__).parent.parent.parent.parent.parent


def _substitute_placeholders(bot: Tux, text: str) -> str:
    """Substitute placeholders in text.

    Available placeholders:
    {member_count} -> Total member count
    {guild_count} -> Total guild count
    {bot_name} -> Bot name
    {bot_version} -> Bot version
    {prefix} -> Bot prefix

    Parameters
    ----------
    text : str
        Text to substitute placeholders in.

    Returns
    -------
    str
        Text with placeholders substituted.
    """
    if not text:
        return text

    with contextlib.suppress(Exception):
        if "{member_count}" in text:
            member_count = sum(guild.member_count or 0 for guild in bot.guilds)
            text = text.replace("{member_count}", str(member_count))
        if "{guild_count}" in text:
            text = text.replace("{guild_count}", str(len(bot.guilds)))
        if "{bot_name}" in text:
            text = text.replace("{bot_name}", CONFIG.BOT_INFO.BOT_NAME)
        if "{bot_version}" in text:
            text = text.replace("{bot_version}", get_version())
        if "{prefix}" in text:
            text = text.replace("{prefix}", CONFIG.get_prefix())
    return text


class Fact(BaseCog):
    """Fact plugin for generating and posting random facts."""

    def __init__(self, bot: Tux) -> None:
        """Initialize the Fact plugin.

        Parameters
        ----------
        bot : Tux
            The bot instance to initialize the plugin with.
        """
        super().__init__(bot)
        self.facts_data: dict[str, dict[str, Any]] = {}
        self._load_facts()
        # Usage is auto-generated by BaseCog

    def _load_facts(self) -> None:
        """Load facts from the facts.toml file."""
        facts_path = workspace_root / "assets" / "data" / "facts.toml"
        try:
            data = tomllib.loads(facts_path.read_text(encoding="utf-8"))
            self.facts_data = data.get("facts", {})
            logger.info(
                f"Loaded the following fact categories from facts.toml: {list(self.facts_data.keys())}",
            )
        except FileNotFoundError:
            logger.warning(f"Facts file not found at {facts_path}")
            self.facts_data = {}
        except Exception as e:
            logger.error(f"Error loading facts: {e}")
            self.facts_data = {}

    async def _fetch_fact(self, fact_type: str) -> tuple[str, str] | None:
        """Fetch a fact of the specified type.

        Parameters
        ----------
        fact_type : str
            The type of fact to fetch.

        Returns
        -------
        tuple[str, str] | None
            A tuple of (fact_text, fact_type) if found, None otherwise.
        """
        ft = fact_type.lower()
        # Determine category key
        if ft == "random":
            key = random.choice(list(self.facts_data)) if self.facts_data else None
        elif ft in self.facts_data:
            key = ft
        else:
            key = next(
                (
                    k
                    for k, data in self.facts_data.items()
                    if _substitute_placeholders(
                        self.bot,
                        data.get("name", k.title()),
                    ).lower()
                    == ft
                ),
                None,
            )
        if not key:
            return None
        cfg = self.facts_data[key]
        disp = _substitute_placeholders(self.bot, cfg.get("name", key.title()))
        # Fetch via API if configured
        if cfg.get("fact_api_url") and cfg.get("fact_api_field"):
            try:
                resp = await http_client.get(cfg["fact_api_url"])
                resp.raise_for_status()
                fact_raw = resp.json().get(cfg["fact_api_field"])
            except Exception:
                fact_raw = None
            fact = _substitute_placeholders(self.bot, fact_raw or "No fact available.")
        else:
            lst = cfg.get("facts", [])
            fact = (
                _substitute_placeholders(self.bot, random.choice(lst))
                if lst
                else "No facts available."
            )
        return fact, disp

    async def fact_type_autocomplete(
        self,
        interaction: discord.Interaction,
        current: str,
    ) -> list[app_commands.Choice[str]]:
        """Provide autocomplete suggestions for fact types.

        Parameters
        ----------
        interaction : discord.Interaction
            The interaction object.
        current : str
            The current user input for filtering.

        Returns
        -------
        list[app_commands.Choice[str]]
            List of autocomplete choices.
        """
        choices = [app_commands.Choice(name="Random", value="random")] + [
            app_commands.Choice(
                name=_substitute_placeholders(self.bot, data.get("name", key.title())),
                value=key,
            )
            for key, data in self.facts_data.items()
        ]
        if current:
            choices = [c for c in choices if current.lower() in c.name.lower()]
        return choices[:25]

    @commands.hybrid_command(name="fact", aliases=["funfact"])
    @app_commands.describe(fact_type="Select the category of fact to retrieve")
    @app_commands.autocomplete(fact_type=fact_type_autocomplete)
    async def fact(self, ctx: commands.Context[Tux], fact_type: str = "random") -> None:
        """Get a fun fact by category or random."""
        res = await self._fetch_fact(fact_type)
        if res:
            fact, category = res
            embed = EmbedCreator.create_embed(
                bot=self.bot,
                embed_type=EmbedCreator.INFO,
                user_name=ctx.author.name,
                user_display_avatar=ctx.author.display_avatar.url,
                title=f"Fun Fact ({category})",
                description=fact,
                custom_author_text="Click here to submit more facts!",
                custom_author_text_url="https://github.com/allthingslinux/tux/blob/main/assets/data/facts.toml",
            )
        else:
            names = [
                _substitute_placeholders(self.bot, data.get("name", key.title()))
                for key, data in self.facts_data.items()
            ]
            embed = EmbedCreator.create_embed(
                bot=self.bot,
                embed_type=EmbedCreator.ERROR,
                user_name=ctx.author.name,
                user_display_avatar=ctx.author.display_avatar.url,
                title="Category Not Found",
                description=f"Invalid category '{fact_type}'. Available: {', '.join(names)}",
            )
        await ctx.send(embed=embed)


async def setup(bot: Tux) -> None:
    """Set up the Fact cog.

    Parameters
    ----------
    bot : Tux
        The bot instance to add the cog to.
    """
    await bot.add_cog(Fact(bot))
