"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Annotated
from pydantic import BeforeValidator

__all__ = ("StrAsPath", "FIELD_TYPE_MAP")
StrAsPath = Annotated[Path, BeforeValidator(lambda v: Path(v))]
FIELD_TYPE_MAP = ...
