"""
This type stub file was generated by pyright.
"""

import sys
from pathlib import Path
from typing import Any, Optional, Self, TYPE_CHECKING, TypeVar, Union
from pydantic import BaseModel
from pydantic.fields import FieldInfo
from pydantic_settings import BaseSettings
from pydantic_settings_export.settings import PSESettings

UnionTypes: tuple[Any, ...] = ...
if sys.version_info < (3, 11):
    ...
else:
    ...
if TYPE_CHECKING:
    ...
else:
    ...
__all__ = ("FieldInfoModel", "SettingsInfoModel")
BASE_SETTINGS_DOCS = ...
BASE_MODEL_DOCS = ...
def value_to_jsonable(value: Any, value_type: Optional[type] = ...) -> Any:
    ...

P = TypeVar("P", bound=Path)
def get_type_by_annotation(annotation: Any, remove_none: bool = ...) -> list[str]:
    ...

def default_path(default: P, global_settings: Optional[PSESettings] = ...) -> P:
    ...

class FieldInfoModel(BaseModel):
    """Info about the field of the settings model."""
    model_config = ...
    name: str = ...
    types: list[str] = ...
    default: Optional[str] = ...
    description: Optional[str] = ...
    examples: list[str] = ...
    aliases: list[str] = ...
    deprecated: bool = ...
    @property
    def full_name(self) -> str:
        """Get the full name (aliased or not) of the field."""
        ...
    
    @property
    def is_required(self) -> bool:
        """Check if the field is required."""
        ...
    
    def has_examples(self) -> bool:
        """Check if the field has examples."""
        ...
    
    @staticmethod
    def create_default(field: FieldInfo, global_settings: Optional[PSESettings] = ...) -> Optional[str]:
        """Make the default value for the field.

        :param field: The field info to generate the default value for.
        :param global_settings: The global settings.
        :return: The default value for the field as a string, or None if there is no default value.
        """
        ...
    
    @classmethod
    def from_settings_field(cls, name: str, field: FieldInfo, global_settings: Optional[PSESettings] = ...) -> Self:
        """Generate FieldInfoModel using name and field.

        :param name: The name of the field.
        :param field: The field info to generate FieldInfoModel from.
        :param global_settings: The global settings.
        :return: Instance of FieldInfoModel.
        """
        ...
    


class SettingsInfoModel(BaseModel):
    """Info about the settings model."""
    name: str = ...
    docs: str = ...
    env_prefix: str = ...
    fields: list[FieldInfoModel] = ...
    child_settings: list[SettingsInfoModel] = ...
    @classmethod
    def from_settings_model(cls, settings: Union[BaseSettings, type[BaseSettings]], global_settings: Optional[PSESettings] = ..., prefix: str = ..., nested_delimiter: str = ...) -> Self:
        """Generate the SettingsInfoModel using a settings model.

        :param settings: The settings model to generate SettingsInfoModel from.
        :param global_settings: The global settings.
        :param prefix: The prefix of the environment variables.
        :param nested_delimiter: The delimiter to use for nested settings.
        :return: Instance of SettingsInfoModel.
        """
        ...
    


