"""
This type stub file was generated by pyright.
"""

from pydantic_settings import BaseSettings
from pydantic_settings.sources import PydanticBaseSettingsSource

__all__ = ("TomlSettings", )
class TomlSettings(BaseSettings):
    """The sources mixin."""
    @classmethod
    def settings_customise_sources(cls, settings_cls: type[BaseSettings], init_settings: PydanticBaseSettingsSource, env_settings: PydanticBaseSettingsSource, dotenv_settings: PydanticBaseSettingsSource, file_secret_settings: PydanticBaseSettingsSource) -> tuple[PydanticBaseSettingsSource, ...]:
        """Customise the sources.

        :param settings_cls: The settings class.
        :param init_settings: The init settings source.
        :param env_settings: The env settings source.
        :param dotenv_settings: The dotenv settings source.
        :param file_secret_settings: The file secret settings source.
        :return: The customised sources.
        """
        ...
    


