"""
This type stub file was generated by pyright.
"""

import argparse
from collections.abc import Sequence
from typing import Any, Optional, Union
from pydantic_settings import BaseSettings

__all__ = ("make_pretty_md_table", "make_pretty_md_table_from_dict")
MARKDOWN_PIPE_RE = ...
def make_pretty_md_table(headers: list[str], rows: list[list[str]]) -> str:
    """Make a pretty Markdown table with column alignment.

    :param headers: The header of the table.
    :param rows: The rows of the table.
    :return: The prettied Markdown table.
    """
    ...

def make_pretty_md_table_from_dict(data: list[dict[str, Optional[str]]], headers: Optional[list[str]] = ...) -> str:
    """Make a pretty Markdown table with column alignment from a list of dictionaries.

    :param data: The rows of the table as dictionaries.
    :param headers: The headers of the table.
    :return: The prettied Markdown table.
    """
    ...

def q(s: Any) -> str:
    """Add quotes around the string."""
    ...

class ObjectImportAction(argparse.Action):
    """Import the object from the module."""
    @staticmethod
    def callback(obj: Any) -> Any:
        """Check if the object is a settings class."""
        ...
    
    @staticmethod
    def import_obj(value: str) -> Any:
        """Import the object from the module.

        :param value: The value in the format is 'module:class'.
        :raise ValueError: If the value is not in the format 'module:class'.
        :raise ValueError: If the class is not in the module.
        :raise ModuleNotFoundError: If the module is not found.
        :return: The imported object.
        """
        ...
    
    def __call__(self, parser: argparse.ArgumentParser, namespace: argparse.Namespace, values: Optional[Union[str, Sequence[Any]]], option_string: Optional[str] = ...) -> None:
        """Import the object from the module."""
        ...
    


class MissingSettingsError(ValueError):
    """Raised when the settings are missing."""
    def __init__(self, missing: dict[Union[str, int], str], settings_path: str = ...) -> None:
        ...
    


def import_settings_from_string(value: str) -> BaseSettings:
    """Import the settings from the string."""
    ...

