"""
This type stub file was generated by pyright.
"""

from shutil import get_terminal_size as get_terminal_size
from click.exceptions import Abort as Abort, BadParameter as BadParameter, Exit as Exit
from click.termui import clear as clear, confirm as confirm, echo_via_pager as echo_via_pager, edit as edit, getchar as getchar, pause as pause, progressbar as progressbar, prompt as prompt, secho as secho, style as style, unstyle as unstyle
from click.utils import echo as echo, format_filename as format_filename, get_app_dir as get_app_dir, get_binary_stream as get_binary_stream, get_text_stream as get_text_stream, open_file as open_file
from . import colors as colors
from .main import Typer as Typer, launch as launch, run as run
from .models import CallbackParam as CallbackParam, Context as Context, FileBinaryRead as FileBinaryRead, FileBinaryWrite as FileBinaryWrite, FileText as FileText, FileTextWrite as FileTextWrite
from .params import Argument as Argument, Option as Option

"""Typer, build great CLIs. Easy to code. Based on Python type hints."""
__version__ = ...
