"""
This type stub file was generated by pyright.
"""

import click
from typing import Any, MutableMapping, Tuple
from .models import ParamMeta

_click_patched = ...
def get_completion_inspect_parameters() -> Tuple[ParamMeta, ParamMeta]:
    ...

def install_callback(ctx: click.Context, param: click.Parameter, value: Any) -> Any:
    ...

def show_callback(ctx: click.Context, param: click.Parameter, value: Any) -> Any:
    ...

def shell_complete(cli: click.Command, ctx_args: MutableMapping[str, Any], prog_name: str, complete_var: str, instruction: str) -> int:
    ...

