"""
This type stub file was generated by pyright.
"""

from typing import Any, IO, Mapping, Optional, Sequence, Union
from click.testing import CliRunner as ClickCliRunner, Result
from typer.main import Typer

class CliRunner(ClickCliRunner):
    def invoke(self, app: Typer, args: Optional[Union[str, Sequence[str]]] = ..., input: Optional[Union[bytes, str, IO[Any]]] = ..., env: Optional[Mapping[str, str]] = ..., catch_exceptions: bool = ..., color: bool = ..., **extra: Any) -> Result:
        ...
    


