"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Dict, Type
from .models import ParamMeta, ParameterInfo

class AnnotatedParamWithDefaultValueError(Exception):
    argument_name: str
    param_type: Type[ParameterInfo]
    def __init__(self, argument_name: str, param_type: Type[ParameterInfo]) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class MixedAnnotatedAndDefaultStyleError(Exception):
    argument_name: str
    annotated_param_type: Type[ParameterInfo]
    default_param_type: Type[ParameterInfo]
    def __init__(self, argument_name: str, annotated_param_type: Type[ParameterInfo], default_param_type: Type[ParameterInfo]) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class MultipleTyperAnnotationsError(Exception):
    argument_name: str
    def __init__(self, argument_name: str) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class DefaultFactoryAndDefaultValueError(Exception):
    argument_name: str
    param_type: Type[ParameterInfo]
    def __init__(self, argument_name: str, param_type: Type[ParameterInfo]) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


def get_params_from_function(func: Callable[..., Any]) -> Dict[str, ParamMeta]:
    ...

