"""
This type stub file was generated by pyright.
"""

from .abc import Page
from .buttons import ReactionButton, ViewButton
from .core import ReactionMenu
from .views_menu import ViewMenu, ViewSelect

"""
reactionmenu • discord pagination
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

A library to create a discord.py 2.0+ paginator. Supports pagination with buttons, reactions, and category selection using selects.

:copyright: (c) 2021-present @defxult
:license: MIT

"""
__source__ = ...
__all__ = ("ReactionMenu", "ReactionButton", "ViewMenu", "ViewButton", "ViewSelect", "Page")
