"""
Revision ID: 55296ad22e23
Revises:
Create Date: 2025-12-01 20:53:03.942766+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "55296ad22e23"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guild",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("guild_joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("case_count", sa.Integer(), nullable=False),
        sa.CheckConstraint("case_count >= 0", name="check_case_count_positive"),
        sa.CheckConstraint("id > 0", name="check_guild_id_valid"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("guild", schema=None) as batch_op:
        batch_op.create_index("idx_guild_id", ["id"], unique=False)

    op.create_table(
        "afk",
        sa.Column("member_id", sa.BigInteger(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "nickname", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "reason", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column("since", sa.DateTime(timezone=True), nullable=False),
        sa.Column("until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("enforced", sa.Boolean(), nullable=False),
        sa.Column("perm_afk", sa.Boolean(), nullable=False),
        sa.CheckConstraint("guild_id > 0", name="check_afk_guild_id_valid"),
        sa.CheckConstraint("member_id > 0", name="check_afk_member_id_valid"),
        sa.CheckConstraint(
            "until IS NULL OR until > since", name="check_afk_until_after_since"
        ),
        sa.ForeignKeyConstraint(["guild_id"], ["guild.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("member_id", "guild_id"),
    )
    with op.batch_alter_table("afk", schema=None) as batch_op:
        batch_op.create_index("idx_afk_enforced", ["enforced"], unique=False)
        batch_op.create_index(
            "idx_afk_expiring",
            ["until"],
            unique=False,
            postgresql_where="until IS NOT NULL AND perm_afk = FALSE",
        )
        batch_op.create_index("idx_afk_guild", ["guild_id"], unique=False)
        batch_op.create_index("idx_afk_member", ["member_id"], unique=False)
        batch_op.create_index("idx_afk_perm", ["perm_afk"], unique=False)
        batch_op.create_index("idx_afk_until", ["until"], unique=False)

    op.create_table(
        "cases",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("case_status", sa.Boolean(), nullable=False),
        sa.Column("case_processed", sa.Boolean(), nullable=False),
        sa.Column(
            "case_type",
            sa.Enum(
                "BAN",
                "UNBAN",
                "HACKBAN",
                "TEMPBAN",
                "KICK",
                "TIMEOUT",
                "UNTIMEOUT",
                "WARN",
                "JAIL",
                "UNJAIL",
                "SNIPPETBAN",
                "SNIPPETUNBAN",
                "POLLBAN",
                "POLLUNBAN",
                name="case_type_enum",
            ),
            nullable=True,
        ),
        sa.Column(
            "case_reason", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False
        ),
        sa.Column("case_moderator_id", sa.BigInteger(), nullable=False),
        sa.Column("case_user_id", sa.BigInteger(), nullable=False),
        sa.Column("case_user_roles", sa.JSON(), nullable=False),
        sa.Column("case_number", sa.Integer(), nullable=True),
        sa.Column("case_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("case_metadata", sa.JSON(), nullable=True),
        sa.Column("mod_log_message_id", sa.BigInteger(), nullable=True),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "case_moderator_id > 0", name="check_case_moderator_id_valid"
        ),
        sa.CheckConstraint(
            "case_number IS NULL OR case_number >= 1", name="check_case_number_positive"
        ),
        sa.CheckConstraint("case_user_id > 0", name="check_case_user_id_valid"),
        sa.CheckConstraint("guild_id > 0", name="check_case_guild_id_valid"),
        sa.CheckConstraint(
            "mod_log_message_id IS NULL OR mod_log_message_id > 0",
            name="check_mod_msg_id_valid",
        ),
        sa.ForeignKeyConstraint(["guild_id"], ["guild.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "guild_id", "case_number", name="uq_case_guild_case_number"
        ),
    )
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.create_index(
            "idx_case_active_guild",
            ["guild_id"],
            unique=False,
            postgresql_where="case_status = TRUE",
        )
        batch_op.create_index("idx_case_expires_at", ["case_expires_at"], unique=False)
        batch_op.create_index("idx_case_guild", ["guild_id"], unique=False)
        batch_op.create_index(
            "idx_case_guild_moderator", ["guild_id", "case_moderator_id"], unique=False
        )
        batch_op.create_index(
            "idx_case_guild_user", ["guild_id", "case_user_id"], unique=False
        )
        batch_op.create_index("idx_case_number", ["case_number"], unique=False)
        batch_op.create_index("idx_case_processed", ["case_processed"], unique=False)
        batch_op.create_index("idx_case_status", ["case_status"], unique=False)
        batch_op.create_index("idx_case_type", ["case_type"], unique=False)
        batch_op.create_index(
            "idx_case_unprocessed_expiring",
            ["case_expires_at"],
            unique=False,
            postgresql_where="case_processed = FALSE AND case_expires_at IS NOT NULL",
        )

    op.create_table(
        "guild_config",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("prefix", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
        sa.Column("mod_log_id", sa.BigInteger(), nullable=True),
        sa.Column("audit_log_id", sa.BigInteger(), nullable=True),
        sa.Column("join_log_id", sa.BigInteger(), nullable=True),
        sa.Column("private_log_id", sa.BigInteger(), nullable=True),
        sa.Column("report_log_id", sa.BigInteger(), nullable=True),
        sa.Column("dev_log_id", sa.BigInteger(), nullable=True),
        sa.Column("jail_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("jail_role_id", sa.BigInteger(), nullable=True),
        sa.Column("onboarding_completed", sa.Boolean(), nullable=False),
        sa.Column(
            "onboarding_stage",
            sa.Enum(
                "NOT_STARTED",
                "DISCOVERED",
                "INITIALIZED",
                "CONFIGURED",
                "COMPLETED",
                name="onboarding_stage_enum",
            ),
            nullable=True,
        ),
        sa.CheckConstraint(
            "audit_log_id IS NULL OR audit_log_id > 0", name="check_audit_log_id_valid"
        ),
        sa.CheckConstraint(
            "dev_log_id IS NULL OR dev_log_id > 0", name="check_dev_log_id_valid"
        ),
        sa.CheckConstraint("id > 0", name="check_guild_config_guild_id_valid"),
        sa.CheckConstraint(
            "jail_channel_id IS NULL OR jail_channel_id > 0",
            name="check_jail_channel_id_valid",
        ),
        sa.CheckConstraint(
            "jail_role_id IS NULL OR jail_role_id > 0", name="check_jail_role_id_valid"
        ),
        sa.CheckConstraint(
            "join_log_id IS NULL OR join_log_id > 0", name="check_join_log_id_valid"
        ),
        sa.CheckConstraint("length(prefix) > 0", name="check_prefix_not_empty"),
        sa.CheckConstraint(
            "mod_log_id IS NULL OR mod_log_id > 0", name="check_mod_log_id_valid"
        ),
        sa.CheckConstraint(
            "private_log_id IS NULL OR private_log_id > 0",
            name="check_private_log_id_valid",
        ),
        sa.CheckConstraint(
            "report_log_id IS NULL OR report_log_id > 0",
            name="check_report_log_id_valid",
        ),
        sa.ForeignKeyConstraint(["id"], ["guild.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "levels",
        sa.Column("member_id", sa.BigInteger(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("xp", sa.Float(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("blacklisted", sa.Boolean(), nullable=False),
        sa.Column("last_message", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("guild_id > 0", name="check_levels_guild_id_valid"),
        sa.CheckConstraint("level >= 0", name="check_level_positive"),
        sa.CheckConstraint("member_id > 0", name="check_levels_member_id_valid"),
        sa.CheckConstraint("xp >= 0", name="check_xp_positive"),
        sa.ForeignKeyConstraint(["guild_id"], ["guild.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("member_id", "guild_id"),
    )
    with op.batch_alter_table("levels", schema=None) as batch_op:
        batch_op.create_index(
            "idx_levels_active_leaderboard",
            ["guild_id", "xp"],
            unique=False,
            postgresql_where="blacklisted = FALSE",
        )
        batch_op.create_index("idx_levels_blacklisted", ["blacklisted"], unique=False)
        batch_op.create_index("idx_levels_guild_xp", ["guild_id", "xp"], unique=False)
        batch_op.create_index("idx_levels_last_message", ["last_message"], unique=False)
        batch_op.create_index("idx_levels_level", ["level"], unique=False)
        batch_op.create_index("idx_levels_member", ["member_id"], unique=False)

    op.create_table(
        "permission_commands",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "command_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column("required_rank", sa.Integer(), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.CheckConstraint(
            "guild_id > 0", name="check_permission_command_guild_id_valid"
        ),
        sa.CheckConstraint(
            "length(command_name) > 0", name="check_command_name_not_empty"
        ),
        sa.CheckConstraint(
            "required_rank >= 0 AND required_rank <= 10",
            name="check_required_rank_range",
        ),
        sa.ForeignKeyConstraint(["guild_id"], ["guild.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "guild_id", "command_name", name="unique_permission_command"
        ),
    )
    with op.batch_alter_table("permission_commands", schema=None) as batch_op:
        batch_op.create_index(
            "idx_permission_commands_guild", ["guild_id"], unique=False
        )
        batch_op.create_index(
            "idx_permission_commands_rank", ["required_rank"], unique=False
        )

    op.create_table(
        "permission_ranks",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.CheckConstraint("guild_id > 0", name="check_permission_rank_guild_id_valid"),
        sa.CheckConstraint("length(name) > 0", name="check_rank_name_not_empty"),
        sa.CheckConstraint("rank >= 0 AND rank <= 10", name="check_rank_range"),
        sa.ForeignKeyConstraint(["guild_id"], ["guild.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guild_id", "name", name="unique_permission_rank_name"),
        sa.UniqueConstraint("guild_id", "rank", name="unique_permission_rank"),
    )
    with op.batch_alter_table("permission_ranks", schema=None) as batch_op:
        batch_op.create_index("idx_permission_ranks_guild", ["guild_id"], unique=False)
        batch_op.create_index("idx_permission_ranks_rank", ["rank"], unique=False)

    op.create_table(
        "reminder",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "reminder_content",
            sqlmodel.sql.sqltypes.AutoString(length=2000),
            nullable=False,
        ),
        sa.Column("reminder_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reminder_channel_id", sa.BigInteger(), nullable=False),
        sa.Column("reminder_user_id", sa.BigInteger(), nullable=False),
        sa.Column("reminder_sent", sa.Boolean(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("guild_id > 0", name="check_reminder_guild_id_valid"),
        sa.CheckConstraint(
            "reminder_channel_id > 0", name="check_reminder_channel_id_valid"
        ),
        sa.CheckConstraint("reminder_user_id > 0", name="check_reminder_user_id_valid"),
        sa.ForeignKeyConstraint(["guild_id"], ["guild.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reminder", schema=None) as batch_op:
        batch_op.create_index(
            "idx_reminder_expires_at", ["reminder_expires_at"], unique=False
        )
        batch_op.create_index("idx_reminder_guild", ["guild_id"], unique=False)
        batch_op.create_index(
            "idx_reminder_guild_expires",
            ["guild_id", "reminder_expires_at"],
            unique=False,
        )
        batch_op.create_index(
            "idx_reminder_guild_sent", ["guild_id", "reminder_sent"], unique=False
        )
        batch_op.create_index(
            "idx_reminder_pending",
            ["reminder_expires_at"],
            unique=False,
            postgresql_where="reminder_sent = FALSE",
        )
        batch_op.create_index("idx_reminder_sent", ["reminder_sent"], unique=False)
        batch_op.create_index("idx_reminder_user", ["reminder_user_id"], unique=False)

    op.create_table(
        "snippet",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "snippet_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "snippet_content",
            sqlmodel.sql.sqltypes.AutoString(length=4000),
            nullable=True,
        ),
        sa.Column("snippet_user_id", sa.BigInteger(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("uses", sa.Integer(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("alias", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.CheckConstraint("guild_id > 0", name="check_snippet_guild_id_valid"),
        sa.CheckConstraint(
            "length(snippet_name) > 0", name="check_snippet_name_not_empty"
        ),
        sa.CheckConstraint("snippet_user_id > 0", name="check_snippet_user_id_valid"),
        sa.CheckConstraint("uses >= 0", name="check_snippet_uses_positive"),
        sa.ForeignKeyConstraint(["guild_id"], ["guild.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("snippet", schema=None) as batch_op:
        batch_op.create_index("idx_snippet_guild", ["guild_id"], unique=False)
        batch_op.create_index("idx_snippet_locked", ["locked"], unique=False)
        batch_op.create_index(
            "idx_snippet_name_guild", ["snippet_name", "guild_id"], unique=True
        )
        batch_op.create_index("idx_snippet_user", ["snippet_user_id"], unique=False)
        batch_op.create_index("idx_snippet_uses", ["uses"], unique=False)

    op.create_table(
        "starboard",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("starboard_channel_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "starboard_emoji",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column("starboard_threshold", sa.Integer(), nullable=False),
        sa.CheckConstraint("id > 0", name="check_starboard_guild_id_valid"),
        sa.CheckConstraint(
            "starboard_channel_id > 0", name="check_starboard_channel_id_valid"
        ),
        sa.CheckConstraint(
            "starboard_threshold >= 1", name="check_starboard_threshold_positive"
        ),
        sa.ForeignKeyConstraint(["id"], ["guild.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("starboard", schema=None) as batch_op:
        batch_op.create_index(
            "idx_starboard_channel", ["starboard_channel_id"], unique=False
        )
        batch_op.create_index(
            "idx_starboard_threshold", ["starboard_threshold"], unique=False
        )

    op.create_table(
        "starboard_message",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "message_content",
            sqlmodel.sql.sqltypes.AutoString(length=4000),
            nullable=False,
        ),
        sa.Column("message_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("message_channel_id", sa.BigInteger(), nullable=False),
        sa.Column("message_user_id", sa.BigInteger(), nullable=False),
        sa.Column("message_guild_id", sa.BigInteger(), nullable=False),
        sa.Column("star_count", sa.Integer(), nullable=False),
        sa.Column("starboard_message_id", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("id > 0", name="check_starboard_msg_id_valid"),
        sa.CheckConstraint(
            "message_channel_id > 0", name="check_starboard_msg_channel_id_valid"
        ),
        sa.CheckConstraint(
            "message_guild_id > 0", name="check_starboard_msg_guild_id_valid"
        ),
        sa.CheckConstraint(
            "message_user_id > 0", name="check_starboard_msg_user_id_valid"
        ),
        sa.CheckConstraint("star_count >= 0", name="check_star_count_positive"),
        sa.CheckConstraint(
            "starboard_message_id > 0", name="check_starboard_post_id_valid"
        ),
        sa.ForeignKeyConstraint(["message_guild_id"], ["guild.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("starboard_message", schema=None) as batch_op:
        batch_op.create_index(
            "idx_starboard_msg_channel", ["message_channel_id"], unique=False
        )
        batch_op.create_index(
            "idx_starboard_msg_expires", ["message_expires_at"], unique=False
        )
        batch_op.create_index(
            "idx_starboard_msg_guild", ["message_guild_id"], unique=False
        )
        batch_op.create_index(
            "idx_starboard_msg_star_count", ["star_count"], unique=False
        )
        batch_op.create_index(
            "idx_starboard_msg_user", ["message_user_id"], unique=False
        )
        batch_op.create_index(
            "ux_starboard_message", ["id", "message_guild_id"], unique=True
        )

    op.create_table(
        "permission_assignments",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("permission_rank_id", sa.BigInteger(), nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("guild_id > 0", name="check_assignment_guild_id_valid"),
        sa.CheckConstraint("role_id > 0", name="check_assignment_role_id_valid"),
        sa.ForeignKeyConstraint(["guild_id"], ["guild.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["permission_rank_id"], ["permission_ranks.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guild_id", "role_id", name="unique_permission_assignment"),
    )
    with op.batch_alter_table("permission_assignments", schema=None) as batch_op:
        batch_op.create_index(
            "idx_permission_assignments_guild", ["guild_id"], unique=False
        )
        batch_op.create_index(
            "idx_permission_assignments_rank", ["permission_rank_id"], unique=False
        )
        batch_op.create_index(
            "idx_permission_assignments_role", ["role_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("permission_assignments", schema=None) as batch_op:
        batch_op.drop_index("idx_permission_assignments_role")
        batch_op.drop_index("idx_permission_assignments_rank")
        batch_op.drop_index("idx_permission_assignments_guild")

    op.drop_table("permission_assignments")
    with op.batch_alter_table("starboard_message", schema=None) as batch_op:
        batch_op.drop_index("ux_starboard_message")
        batch_op.drop_index("idx_starboard_msg_user")
        batch_op.drop_index("idx_starboard_msg_star_count")
        batch_op.drop_index("idx_starboard_msg_guild")
        batch_op.drop_index("idx_starboard_msg_expires")
        batch_op.drop_index("idx_starboard_msg_channel")

    op.drop_table("starboard_message")
    with op.batch_alter_table("starboard", schema=None) as batch_op:
        batch_op.drop_index("idx_starboard_threshold")
        batch_op.drop_index("idx_starboard_channel")

    op.drop_table("starboard")
    with op.batch_alter_table("snippet", schema=None) as batch_op:
        batch_op.drop_index("idx_snippet_uses")
        batch_op.drop_index("idx_snippet_user")
        batch_op.drop_index("idx_snippet_name_guild")
        batch_op.drop_index("idx_snippet_locked")
        batch_op.drop_index("idx_snippet_guild")

    op.drop_table("snippet")
    with op.batch_alter_table("reminder", schema=None) as batch_op:
        batch_op.drop_index("idx_reminder_user")
        batch_op.drop_index("idx_reminder_sent")
        batch_op.drop_index(
            "idx_reminder_pending", postgresql_where="reminder_sent = FALSE"
        )
        batch_op.drop_index("idx_reminder_guild_sent")
        batch_op.drop_index("idx_reminder_guild_expires")
        batch_op.drop_index("idx_reminder_guild")
        batch_op.drop_index("idx_reminder_expires_at")

    op.drop_table("reminder")
    with op.batch_alter_table("permission_ranks", schema=None) as batch_op:
        batch_op.drop_index("idx_permission_ranks_rank")
        batch_op.drop_index("idx_permission_ranks_guild")

    op.drop_table("permission_ranks")
    with op.batch_alter_table("permission_commands", schema=None) as batch_op:
        batch_op.drop_index("idx_permission_commands_rank")
        batch_op.drop_index("idx_permission_commands_guild")

    op.drop_table("permission_commands")
    with op.batch_alter_table("levels", schema=None) as batch_op:
        batch_op.drop_index("idx_levels_member")
        batch_op.drop_index("idx_levels_level")
        batch_op.drop_index("idx_levels_last_message")
        batch_op.drop_index("idx_levels_guild_xp")
        batch_op.drop_index("idx_levels_blacklisted")
        batch_op.drop_index(
            "idx_levels_active_leaderboard", postgresql_where="blacklisted = FALSE"
        )

    op.drop_table("levels")
    op.drop_table("guild_config")
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_index(
            "idx_case_unprocessed_expiring",
            postgresql_where="case_processed = FALSE AND case_expires_at IS NOT NULL",
        )
        batch_op.drop_index("idx_case_type")
        batch_op.drop_index("idx_case_status")
        batch_op.drop_index("idx_case_processed")
        batch_op.drop_index("idx_case_number")
        batch_op.drop_index("idx_case_guild_user")
        batch_op.drop_index("idx_case_guild_moderator")
        batch_op.drop_index("idx_case_guild")
        batch_op.drop_index("idx_case_expires_at")
        batch_op.drop_index(
            "idx_case_active_guild", postgresql_where="case_status = TRUE"
        )

    op.drop_table("cases")
    with op.batch_alter_table("afk", schema=None) as batch_op:
        batch_op.drop_index("idx_afk_until")
        batch_op.drop_index("idx_afk_perm")
        batch_op.drop_index("idx_afk_member")
        batch_op.drop_index("idx_afk_guild")
        batch_op.drop_index(
            "idx_afk_expiring",
            postgresql_where="until IS NOT NULL AND perm_afk = FALSE",
        )
        batch_op.drop_index("idx_afk_enforced")

    op.drop_table("afk")
    with op.batch_alter_table("guild", schema=None) as batch_op:
        batch_op.drop_index("idx_guild_id")

    op.drop_table("guild")
    # ### end Alembic commands ###
