"""
Revision ID: b83284093e38
Revises: 0b3288704dea
Create Date: 2026-01-23 18:11:35.503658+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b83284093e38"
down_revision: Union[str, None] = "0b3288704dea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.create_index(
            "idx_case_jail_unjail",
            ["guild_id", "case_user_id", "case_type", "id"],
            unique=False,
            postgresql_where="case_type IN ('JAIL', 'UNJAIL')",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_index(
            "idx_case_jail_unjail", postgresql_where="case_type IN ('JAIL', 'UNJAIL')"
        )

    # ### end Alembic commands ###
