"""
Revision ID: 0b3288704dea
Revises: 12e5d7b32ddf
Create Date: 2026-01-23 01:38:08.997696+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "0b3288704dea"
down_revision: Union[str, None] = "12e5d7b32ddf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.create_index(
            "idx_case_expired_tempbans",
            ["guild_id", "case_type", "case_status", "case_expires_at"],
            unique=False,
            postgresql_where="case_type = 'TEMPBAN' AND case_status = TRUE AND case_processed = FALSE AND case_expires_at IS NOT NULL",
        )
        batch_op.create_index(
            "idx_case_guild_number", ["guild_id", "case_number"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_index("idx_case_guild_number")
        batch_op.drop_index(
            "idx_case_expired_tempbans",
            postgresql_where="case_type = 'TEMPBAN' AND case_status = TRUE AND case_processed = FALSE AND case_expires_at IS NOT NULL",
        )

    # ### end Alembic commands ###
