"""
Revision ID: 9611b8891e59
Revises: 
Create Date: 2025-10-17 01:25:05.139739+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9611b8891e59'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('case_count', sa.Integer(), nullable=False),
    sa.Column('guild_metadata', sa.JSON(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('feature_flags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id')
    )
    with op.batch_alter_table('guild', schema=None) as batch_op:
        batch_op.create_index('idx_guild_id', ['guild_id'], unique=False)

    op.create_table('afk',
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('since', sa.DateTime(timezone=True), nullable=False),
    sa.Column('until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('enforced', sa.Boolean(), nullable=False),
    sa.Column('perm_afk', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id')
    )
    with op.batch_alter_table('afk', schema=None) as batch_op:
        batch_op.create_index('idx_afk_enforced', ['enforced'], unique=False)
        batch_op.create_index('idx_afk_guild', ['guild_id'], unique=False)
        batch_op.create_index('idx_afk_member_guild', ['member_id', 'guild_id'], unique=True)
        batch_op.create_index('idx_afk_perm', ['perm_afk'], unique=False)
        batch_op.create_index('idx_afk_until', ['until'], unique=False)

    op.create_table('cases',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('case_status', sa.Boolean(), nullable=False),
    sa.Column('case_processed', sa.Boolean(), nullable=False),
    sa.Column('case_type', sa.Enum('BAN', 'UNBAN', 'HACKBAN', 'TEMPBAN', 'KICK', 'TIMEOUT', 'UNTIMEOUT', 'WARN', 'JAIL', 'UNJAIL', 'SNIPPETBAN', 'SNIPPETUNBAN', 'POLLBAN', 'POLLUNBAN', name='case_type_enum'), nullable=True),
    sa.Column('case_reason', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('case_moderator_id', sa.BigInteger(), nullable=False),
    sa.Column('case_user_id', sa.BigInteger(), nullable=False),
    sa.Column('case_user_roles', sa.JSON(), nullable=False),
    sa.Column('case_number', sa.Integer(), nullable=True),
    sa.Column('case_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('case_metadata', sa.JSON(), nullable=True),
    sa.Column('audit_log_message_id', sa.BigInteger(), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id'),
    sa.UniqueConstraint('guild_id', 'case_number', name='uq_case_guild_case_number')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index('idx_case_expires_at', ['case_expires_at'], unique=False)
        batch_op.create_index('idx_case_guild_moderator', ['guild_id', 'case_moderator_id'], unique=False)
        batch_op.create_index('idx_case_guild_user', ['guild_id', 'case_user_id'], unique=False)
        batch_op.create_index('idx_case_number', ['case_number'], unique=False)
        batch_op.create_index('idx_case_status', ['case_status'], unique=False)
        batch_op.create_index('idx_case_type', ['case_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_case_processed'), ['case_processed'], unique=False)

    op.create_table('guild_command_permissions',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('command_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('required_rank', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.CheckConstraint('required_rank >= 0 AND required_rank <= 100', name='check_required_rank_range'),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'command_name', name='unique_guild_command')
    )
    with op.batch_alter_table('guild_command_permissions', schema=None) as batch_op:
        batch_op.create_index('idx_guild_cmd_perms_category', ['guild_id', 'category'], unique=False)
        batch_op.create_index('idx_guild_cmd_perms_guild', ['guild_id'], unique=False)
        batch_op.create_index('idx_guild_cmd_perms_rank', ['required_rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_guild_command_permissions_command_name'), ['command_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_guild_command_permissions_guild_id'), ['guild_id'], unique=False)

    op.create_table('guild_config',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('mod_log_id', sa.BigInteger(), nullable=True),
    sa.Column('audit_log_id', sa.BigInteger(), nullable=True),
    sa.Column('join_log_id', sa.BigInteger(), nullable=True),
    sa.Column('private_log_id', sa.BigInteger(), nullable=True),
    sa.Column('report_log_id', sa.BigInteger(), nullable=True),
    sa.Column('dev_log_id', sa.BigInteger(), nullable=True),
    sa.Column('jail_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('jail_role_id', sa.BigInteger(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('onboarding_stage', sa.Enum('NOT_STARTED', 'DISCOVERED', 'INITIALIZED', 'CONFIGURED', 'COMPLETED', name='onboarding_stage_enum'), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('guild_permission_ranks',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.CheckConstraint('rank >= 0 AND rank <= 100', name='check_rank_range'),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'name', name='unique_guild_permission_rank_name'),
    sa.UniqueConstraint('guild_id', 'rank', name='unique_guild_permission_rank')
    )
    with op.batch_alter_table('guild_permission_ranks', schema=None) as batch_op:
        batch_op.create_index('idx_guild_perm_ranks_guild', ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guild_permission_ranks_guild_id'), ['guild_id'], unique=False)

    op.create_table('levels',
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('xp', sa.Float(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('blacklisted', sa.Boolean(), nullable=False),
    sa.Column('last_message', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id', 'guild_id')
    )
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.create_index('idx_levels_blacklisted', ['blacklisted'], unique=False)
        batch_op.create_index('idx_levels_guild_xp', ['guild_id', 'xp'], unique=False)
        batch_op.create_index('idx_levels_last_message', ['last_message'], unique=False)
        batch_op.create_index('idx_levels_level', ['level'], unique=False)
        batch_op.create_index('idx_levels_member', ['member_id'], unique=False)

    op.create_table('reminder',
    sa.Column('reminder_id', sa.Integer(), nullable=False),
    sa.Column('reminder_content', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('reminder_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reminder_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('reminder_user_id', sa.BigInteger(), nullable=False),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reminder_id')
    )
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.create_index('idx_reminder_expires_at', ['reminder_expires_at'], unique=False)
        batch_op.create_index('idx_reminder_guild_expires', ['guild_id', 'reminder_expires_at'], unique=False)
        batch_op.create_index('idx_reminder_sent', ['reminder_sent'], unique=False)
        batch_op.create_index('idx_reminder_user', ['reminder_user_id'], unique=False)

    op.create_table('snippet',
    sa.Column('snippet_id', sa.Integer(), nullable=False),
    sa.Column('snippet_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('snippet_content', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('snippet_user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snippet_id')
    )
    with op.batch_alter_table('snippet', schema=None) as batch_op:
        batch_op.create_index('idx_snippet_name_guild', ['snippet_name', 'guild_id'], unique=True)
        batch_op.create_index('idx_snippet_user', ['snippet_user_id'], unique=False)
        batch_op.create_index('idx_snippet_uses', ['uses'], unique=False)

    op.create_table('starboard',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('starboard_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('starboard_emoji', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('starboard_threshold', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guild_id')
    )
    with op.batch_alter_table('starboard', schema=None) as batch_op:
        batch_op.create_index('idx_starboard_channel', ['starboard_channel_id'], unique=False)
        batch_op.create_index('idx_starboard_threshold', ['starboard_threshold'], unique=False)

    op.create_table('starboard_message',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('message_content', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
    sa.Column('message_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_user_id', sa.BigInteger(), nullable=False),
    sa.Column('message_guild_id', sa.BigInteger(), nullable=False),
    sa.Column('star_count', sa.Integer(), nullable=False),
    sa.Column('starboard_message_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['message_guild_id'], ['guild.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    with op.batch_alter_table('starboard_message', schema=None) as batch_op:
        batch_op.create_index('idx_starboard_msg_channel', ['message_channel_id'], unique=False)
        batch_op.create_index('idx_starboard_msg_expires', ['message_expires_at'], unique=False)
        batch_op.create_index('idx_starboard_msg_star_count', ['star_count'], unique=False)
        batch_op.create_index('idx_starboard_msg_user', ['message_user_id'], unique=False)
        batch_op.create_index('ux_starboard_message', ['message_id', 'message_guild_id'], unique=True)

    op.create_table('guild_permission_assignments',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_rank_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_by', sa.BigInteger(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.guild_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_rank_id'], ['guild_permission_ranks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'role_id', name='unique_guild_role_assignment')
    )
    with op.batch_alter_table('guild_permission_assignments', schema=None) as batch_op:
        batch_op.create_index('idx_guild_perm_assignments_guild', ['guild_id'], unique=False)
        batch_op.create_index('idx_guild_perm_assignments_rank', ['permission_rank_id'], unique=False)
        batch_op.create_index('idx_guild_perm_assignments_role', ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guild_permission_assignments_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guild_permission_assignments_permission_rank_id'), ['permission_rank_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guild_permission_assignments_role_id'), ['role_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guild_permission_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guild_permission_assignments_role_id'))
        batch_op.drop_index(batch_op.f('ix_guild_permission_assignments_permission_rank_id'))
        batch_op.drop_index(batch_op.f('ix_guild_permission_assignments_guild_id'))
        batch_op.drop_index('idx_guild_perm_assignments_role')
        batch_op.drop_index('idx_guild_perm_assignments_rank')
        batch_op.drop_index('idx_guild_perm_assignments_guild')

    op.drop_table('guild_permission_assignments')
    with op.batch_alter_table('starboard_message', schema=None) as batch_op:
        batch_op.drop_index('ux_starboard_message')
        batch_op.drop_index('idx_starboard_msg_user')
        batch_op.drop_index('idx_starboard_msg_star_count')
        batch_op.drop_index('idx_starboard_msg_expires')
        batch_op.drop_index('idx_starboard_msg_channel')

    op.drop_table('starboard_message')
    with op.batch_alter_table('starboard', schema=None) as batch_op:
        batch_op.drop_index('idx_starboard_threshold')
        batch_op.drop_index('idx_starboard_channel')

    op.drop_table('starboard')
    with op.batch_alter_table('snippet', schema=None) as batch_op:
        batch_op.drop_index('idx_snippet_uses')
        batch_op.drop_index('idx_snippet_user')
        batch_op.drop_index('idx_snippet_name_guild')

    op.drop_table('snippet')
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_index('idx_reminder_user')
        batch_op.drop_index('idx_reminder_sent')
        batch_op.drop_index('idx_reminder_guild_expires')
        batch_op.drop_index('idx_reminder_expires_at')

    op.drop_table('reminder')
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_index('idx_levels_member')
        batch_op.drop_index('idx_levels_level')
        batch_op.drop_index('idx_levels_last_message')
        batch_op.drop_index('idx_levels_guild_xp')
        batch_op.drop_index('idx_levels_blacklisted')

    op.drop_table('levels')
    with op.batch_alter_table('guild_permission_ranks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guild_permission_ranks_guild_id'))
        batch_op.drop_index('idx_guild_perm_ranks_guild')

    op.drop_table('guild_permission_ranks')
    op.drop_table('guild_config')
    with op.batch_alter_table('guild_command_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guild_command_permissions_guild_id'))
        batch_op.drop_index(batch_op.f('ix_guild_command_permissions_command_name'))
        batch_op.drop_index('idx_guild_cmd_perms_rank')
        batch_op.drop_index('idx_guild_cmd_perms_guild')
        batch_op.drop_index('idx_guild_cmd_perms_category')

    op.drop_table('guild_command_permissions')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_case_processed'))
        batch_op.drop_index('idx_case_type')
        batch_op.drop_index('idx_case_status')
        batch_op.drop_index('idx_case_number')
        batch_op.drop_index('idx_case_guild_user')
        batch_op.drop_index('idx_case_guild_moderator')
        batch_op.drop_index('idx_case_expires_at')

    op.drop_table('cases')
    with op.batch_alter_table('afk', schema=None) as batch_op:
        batch_op.drop_index('idx_afk_until')
        batch_op.drop_index('idx_afk_perm')
        batch_op.drop_index('idx_afk_member_guild')
        batch_op.drop_index('idx_afk_guild')
        batch_op.drop_index('idx_afk_enforced')

    op.drop_table('afk')
    with op.batch_alter_table('guild', schema=None) as batch_op:
        batch_op.drop_index('idx_guild_id')

    op.drop_table('guild')
    # ### end Alembic commands ###
