"""
This type stub file was generated by pyright.
"""

from .fixtures import pglite_engine, pglite_session, pglite_sqlalchemy_engine, pglite_sqlalchemy_session
from .manager import SQLAlchemyPGliteManager
from .utils import create_all_tables, drop_all_tables, get_session_class

"""SQLAlchemy integration for py-pglite.

This module provides SQLAlchemy-specific fixtures and utilities for py-pglite.
"""
__all__ = ["SQLAlchemyPGliteManager", "pglite_engine", "pglite_session", "pglite_sqlalchemy_session", "pglite_sqlalchemy_engine", "create_all_tables", "drop_all_tables", "get_session_class"]
