---
name: Setup Python Environment
description: Set up Python with Uv and dependencies
inputs:
  python-version:
    description: Python version to use
    required: false
    default: '3.13'
  uv-version:
    description: Uv version to install (e.g. 0.8.8)
    required: false
    default: 0.8.8
  enable-cache:
    description: Enable uv cache persistence
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    # PYTHON ENVIRONMENT SETUP (use GitHub's cached Python)
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    # UV INSTALLATION
    # Installs uv and optionally enables cache persistence
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: ${{ inputs.enable-cache }}

    # DEPENDENCY INSTALLATION
    # Install project with locked dependencies
    - name: Install dependencies
      shell: bash
      run: uv sync --frozen
