"""
This type stub file was generated by pyright.
"""

import sys
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any, ClassVar, Generic, Optional, TYPE_CHECKING, TypeVar, final
from pydantic import BaseModel
from pydantic_settings_export.settings import PSESettings
from pydantic_settings_export.models import SettingsInfoModel

if sys.version_info < (3, 10):
    ...
else:
    ...
if TYPE_CHECKING:
    ...
else:
    ...
__all__ = ("AbstractGenerator", )
class BaseGeneratorSettings(BaseModel):
    """Base model config for the generator."""
    enabled: bool = ...
    paths: list[Path] = ...
    def __bool__(self) -> bool:
        """Check if the configuration file is set."""
        ...
    


C = TypeVar("C", bound=BaseGeneratorSettings)
class AbstractGenerator(ABC, Generic[C]):
    """The abstract class for the configuration file generator."""
    name: ClassVar[str]
    config: ClassVar[type[BaseGeneratorSettings]]
    ALL_GENERATORS: ClassVar[list[type[AbstractGenerator]]] = ...
    def __init__(self, settings: PSESettings, generator_config: Optional[C] = ...) -> None:
        """Initialize the AbstractGenerator.

        :param settings: The settings for the generator.
        """
        ...
    
    def __init_subclass__(cls, **kwargs: Any) -> None:
        """Initialize the subclass."""
        ...
    
    @abstractmethod
    def generate_single(self, settings_info: SettingsInfoModel, level: int = ...) -> str:
        """Generate the configuration file content.

        :param settings_info: The settings class to generate documentation for.
        :param level: The level of nesting. Used for indentation.
        :return: The generated documentation.
        """
        ...
    
    def generate(self, *settings_infos: SettingsInfoModel) -> str:
        """Generate the configuration file content.

        :param settings_infos: The settings info classes to generate documentation for.
        :return: The generated documentation.
        """
        ...
    
    def file_paths(self) -> list[Path]:
        """Get the list of files which need to create/update.

        :return: The list of files to write.
        This is used to determine if the files need to be written.
        """
        ...
    
    def run(self, *settings_info: SettingsInfoModel) -> list[Path]:
        """Run the generator.

        :param settings_info: The settings info to generate documentation for.
        :return: The list of file paths is written to.
        """
        ...
    
    @staticmethod
    @final
    def generators() -> dict[str, type[AbstractGenerator]]:
        """Get all generators.

        :return: The generators (key: generator name, value: generator class).
        """
        ...
    
    @staticmethod
    @final
    def create_generator_config_model(multiple_for_single: bool = ...) -> type[BaseModel]:
        """Create the generator config model.

        This model contains all the generators' configuration information.
        The attribute is the generator name, the value is generator config.

        :param multiple_for_single: Whether to create a list of the generator config for the single generator.
        :return: The generator model.
        """
        ...
    


