"""
This type stub file was generated by pyright.
"""

import sys
from pathlib import Path
from typing import Literal, Optional, Self
from pydantic import model_validator
from pydantic_settings_export.models import SettingsInfoModel
from .abstract import AbstractGenerator, BaseGeneratorSettings

if sys.version_info < (3, 11):
    ...
else:
    ...
__all__ = ("DotEnvGenerator", )
DotEnvMode = Literal["all", "only-optional", "only-required"]
DOTENV_MODE_MAP: dict[DotEnvMode, tuple[bool, bool]] = ...
DOTENV_MODE_MAP_DEFAULT = ...
class DotEnvSettings(BaseGeneratorSettings):
    """Settings for the .env file."""
    model_config = ...
    name: Optional[Path] = ...
    paths: list[Path] = ...
    split_by_group: bool = ...
    add_examples: bool = ...
    mode: DotEnvMode = ...
    @model_validator(mode="after")
    def validate_paths(self) -> Self:
        """Validate the paths."""
        ...
    


class DotEnvGenerator(AbstractGenerator[DotEnvSettings]):
    """The .env example generator."""
    name = ...
    config = DotEnvSettings
    def generate_single(self, settings_info: SettingsInfoModel, level: int = ...) -> str:
        """Generate a .env example for a pydantic settings class.

        Creates a formatted .env file with:
        - Optional/required variables clearly marked
        - Grouped settings with headers
        - Example values as comments
        - Proper environment variable naming

        :param settings_info: The settings class to generate examples for.
        :param level: The level of nesting for proper formatting.
        :return: Formatted .env content with variables and documentation.
        """
        ...
    


