"""
This type stub file was generated by pyright.
"""

import sys
from pathlib import Path
from typing import Literal, Optional, Self, TYPE_CHECKING, TypedDict, Union
from pydantic import model_validator
from pydantic_settings_export.models import SettingsInfoModel
from .abstract import AbstractGenerator, BaseGeneratorSettings

if sys.version_info < (3, 11):
    ...
else:
    ...
if TYPE_CHECKING:
    ...
__all__ = ("MarkdownGenerator", )
class TableRowDict(TypedDict):
    """The table row dictionary."""
    Name: str
    Type: str
    Default: str
    Description: str
    Example: Optional[str]
    ...


TableHeadersEnum = ...
TableHeaders: list[TableHeadersEnum] = ...
UNION_SEPARATOR = ...
class MarkdownSettings(BaseGeneratorSettings):
    """Settings for the Markdown file."""
    model_config = ...
    name: str = ...
    save_dirs: list[Path] = ...
    paths: list[Path] = ...
    file_prefix: str = ...
    to_upper_case: bool = ...
    table_headers: list[TableHeadersEnum] = ...
    table_only: Union[bool, Literal["with-header"]] = ...
    region: Union[str, Literal[False]] = ...
    @model_validator(mode="after")
    def validate_paths(self) -> Self:
        """Validate the paths."""
        ...
    
    @model_validator(mode="after")
    def validate_region(self) -> Self:
        """Validate the region."""
        ...
    
    def __bool__(self) -> bool:
        """Check if the configuration file is set."""
        ...
    


class MarkdownGenerator(AbstractGenerator[MarkdownSettings]):
    """The Markdown configuration file generator."""
    name = ...
    config = MarkdownSettings
    def generate_single(self, settings_info: SettingsInfoModel, level: int = ...) -> str:
        """Generate Markdown documentation for a pydantic settings class.

        Creates formatted Markdown with:
        - Nested headers for settings hierarchy
        - Tables for settings documentation
        - Environment variable information
        - Type annotations and defaults
        - Optional examples and deprecation notices


        :param settings_info: Settings model to document.
        :param level: Header nesting level (h1, h2, etc.).
        :return: Formatted Markdown documentation.
        """
        ...
    
    def generate(self, *settings_infos: SettingsInfoModel) -> str:
        """Generate Markdown documentation for a pydantic settings class.

        :param settings_infos: The settings class to generate documentation for.
        :return: The generated documentation.
        """
        ...
    
    def run(self, *settings_info: SettingsInfoModel) -> list[Path]:
        """Run the generator.

        :param settings_info: The settings info to generate documentation for.
        :return: The paths to generated documentation.
        """
        ...
    


