"""
This type stub file was generated by pyright.
"""

from pydantic_settings_export.models import SettingsInfoModel
from .abstract import AbstractGenerator, BaseGeneratorSettings

__all__ = ("SimpleGenerator", )
INDENT_CHAR = ...
HEADER_UNDERLINE_CHAR = ...
class SimpleSettings(BaseGeneratorSettings):
    """Settings for the simple generator."""
    model_config = ...


class SimpleGenerator(AbstractGenerator[SimpleSettings]):
    """The Simple generator."""
    name = ...
    config = SimpleSettings
    def generate_single(self, settings_info: SettingsInfoModel, level: int = ...) -> str:
        """Generate simple text documentation for settings.

        Produces a clean, readable text format with:
        - Section headers with underlines
        - Field descriptions and types
        - Default values and examples
        - Proper spacing and indentation

        :param settings_info: Settings model to document.
        :param level: Nesting level for indentation.
        :return: Formatted text documentation with consistent styling.
        """
        ...
    


