"""
This type stub file was generated by pyright.
"""

def get_emoji_aliases(): # -> dict[Any, Any]:
    '''
    Returns all Emojis as a dict (key = alias, value = unicode).

    :rtype: dict
    '''
    ...

def get_emoji_by_code(code): # -> None:
    '''
    Returns Emoji by Unicode code.

    :param code: Emoji Unicode code.
    :rtype: emojis.db.Emoji
    '''
    ...

def get_emoji_by_alias(alias): # -> Emoji | None:
    '''
    Returns Emoji by alias.

    :param alias: Emoji alias.
    :rtype: emojis.db.Emoji
    '''
    ...

def get_emojis_by_tag(tag): # -> filter[Emoji]:
    '''
    Returns all Emojis from selected tag.

    :param tag: Tag name to filter (case-insensitive).
    :rtype: iter
    '''
    ...

def get_emojis_by_category(category): # -> filter[Any]:
    '''
    Returns all Emojis from selected category.

    :param tag: Category name to filter (case-insensitive).
    :rtype: iter
    '''
    ...

def get_tags(): # -> set[Any]:
    '''
    Returns all tags available.

    :rtype: set
    '''
    ...

def get_categories(): # -> set[Any]:
    '''
    Returns all categories available.

    :rtype: set
    '''
    ...

