site_name: Tux
site_url: https://tux.atl.dev

# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository
repo_url: https://github.com/allthingslinux/tux

# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-name
repo_name: allthingslinux/tux

# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
edit_uri: edit/main/docs/
docs_dir: ./content
site_dir: ../build/docs
extra:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links
  social:
    - icon: fontawesome/solid/globe
      link: https://allthingslinux.org
    - icon: fontawesome/brands/github
      link: https://github.com/allthingslinux/tux
    - icon: fontawesome/brands/discord
      link: https://discord.gg/gpmSjcjQxg
#
### THEME
#
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/mkdocstrings.css
theme:
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/
  language: en

  # https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme
  name: material
  custom_dir: overrides

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#logo
  logo: assets/images/logo.png

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#favicon
  favicon: assets/images/logo.png

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#site-icons
  icon:
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-icon
    repo: fontawesome/brands/github

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  palette:
    scheme: custom
    primary: custom

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/
  font:
    text: Inter
    code: JetBrains Mono
  features:
    ### Navigation
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
    - navigation.instant
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#progress-indicator
    - navigation.instant.progress
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-tracking
    - navigation.tracking
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages-without
    - navigation.indexes
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.top
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.tabs
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#sticky-navigation-tabs
    - navigation.tabs.sticky
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections
    - navigation.sections
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-pruning
    - navigation.prune

    ### Table of Contents
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-following
    - toc.follow

    ### Search
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.suggest
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-highlighting
    - search.highlight

    ### Code Actions
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    - content.action.edit
    - content.code.copy
#
### PLUGINS
#
plugins:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#built-in-search-plugin
  # https://squidfunk.github.io/mkdocs-material/plugins/search/
  - search:
      enabled: true

  # https://mkdocstrings.github.io/autorefs/
  - autorefs:
      # https://mkdocstrings.github.io/autorefs/#non-unique-headings
      resolve_closest: true

  # https://squidfunk.github.io/mkdocs-material/plugins/social/
  - social:
      enabled: true
      cards_layout_options:
        background_color: '#11111B'
        color: '#ffffff'
  - minify:
      minify_html: true
      minify_js: false
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      css_files:
        # https://mkdocstrings.github.io/python/usage/customization/#css-classes
        - assets/stylesheets/extra.css
        - assets/stylesheets/mkdocstrings.css

  # https://mkdocstrings.github.io/
  - mkdocstrings:
      # https://mkdocstrings.github.io/python/usage/#installation
      default_handler: python

      ### Handlers

      # https://mkdocstrings.github.io/python/usage/#configuration
      handlers:
        # https://mkdocstrings.github.io/python/
        python:
          # https://mkdocstrings.github.io/usage/#cross-references-to-other-projects-inventories
          # https://mkdocstrings.github.io/python/usage/#inventories
          inventories:
            # Defaults to latest Python version
            - url: https://docs.python.org/3/objects.inv
            - url: https://discordpy.readthedocs.io/en/stable/objects.inv
          # https://mkdocstrings.github.io/usage/?h=enable_inventory#cross-references-to-other-projects-inventories
          enable_inventory: true
          # https://mkdocstrings.github.io/python/usage/#load_external_modules
          load_external_modules: true
          # https://mkdocstrings.github.io/usage/theming/#templates
          # https://mkdocstrings.github.io/python/usage/customization/#templates
          custom_templates: overrides/python/material

          ### Options
          options:
            ### Extensions
            # https://mkdocstrings.github.io/python/usage/configuration/general/#extensions
            extensions:
              - griffe_generics
              - griffe_inherited_docstrings

            ### General

            # https://mkdocstrings.github.io/python/usage/configuration/general/#allow_inspection
            allow_inspection: true
            # https://mkdocstrings.github.io/python/usage/configuration/general/#find_stubs_package
            find_stubs_package: true
            # https://mkdocstrings.github.io/python/usage/configuration/general/#force_inspection
            force_inspection: false
            # https://mkdocstrings.github.io/python/usage/configuration/general/#show_bases
            show_bases: true
            # https://mkdocstrings.github.io/python/usage/configuration/general/#show_source
            show_source: true

            ### Headings

            # https://mkdocstrings.github.io/python/usage/configuration/headings/#heading_level
            heading_level: 1
            # https://mkdocstrings.github.io/python/usage/configuration/headings/#show_root_heading
            show_root_heading: true
            # https://mkdocstrings.github.io/python/usage/configuration/headings/#show_root_toc_entry
            show_root_toc_entry: true
            # https://mkdocstrings.github.io/python/usage/configuration/headings/#show_root_full_path
            show_root_full_path: true
            # https://mkdocstrings.github.io/python/usage/configuration/headings/#show_root_members_full_path
            show_root_members_full_path: false
            # https://mkdocstrings.github.io/python/usage/configuration/headings/#show_object_full_path
            show_object_full_path: false
            # https://mkdocstrings.github.io/python/usage/configuration/headings/#show_category_heading
            show_category_heading: true
            # https://mkdocstrings.github.io/python/usage/configuration/headings/#show_symbol_type_heading
            show_symbol_type_heading: true
            # https://mkdocstrings.github.io/python/usage/configuration/headings/#show_symbol_type_toc
            show_symbol_type_toc: true

            ### Members

            # https://mkdocstrings.github.io/python/usage/configuration/members/#members_order
            members_order: source
            # https://mkdocstrings.github.io/python/usage/configuration/members/#filters
            filters: []
            # https://mkdocstrings.github.io/python/usage/configuration/members/#group_by_category
            group_by_category: true
            # https://mkdocstrings.github.io/python/usage/configuration/members/#show_submodules
            show_submodules: false
            # https://mkdocstrings.github.io/python/usage/configuration/members/#summary
            summary: true
            # https://mkdocstrings.github.io/python/usage/configuration/members/#show_labels
            show_labels: true

            ### Docstrings

            # https://mkdocstrings.github.io/python/usage/configuration/docstrings/#docstring_style
            docstring_style: numpy
            # https://mkdocstrings.github.io/python/usage/configuration/docstrings/#docstring_options
            docstring_options:
              ignore_init_summary: false
              trim_doctest_flags: true
              returns_multiple_items: true
            # https://mkdocstrings.github.io/python/usage/configuration/docstrings/#docstring_section_style
            docstring_section_style: table
            # https://mkdocstrings.github.io/python/usage/configuration/docstrings/#merge_init_into_class
            merge_init_into_class: true
            # https://mkdocstrings.github.io/python/usage/configuration/docstrings/#show_if_no_docstring
            show_if_no_docstring: false
            # https://mkdocstrings.github.io/python/usage/configuration/docstrings/#show_docstring_attributes
            show_docstring_attributes: true
            # https://mkdocstrings.github.io/python/usage/configuration/docstrings/#show_docstring_functions
            show_docstring_functions: true
            # https://mkdocstrings.github.io/python/usage/configuration/docstrings/#show_docstring_classes
            show_docstring_classes: true
            # https://mkdocstrings.github.io/python/usage/configuration/docstrings/#show_docstring_modules
            show_docstring_modules: true
            # https://mkdocstrings.github.io/python/usage/configuration/docstrings/#show_docstring_description
            show_docstring_description: true
            # https://mkdocstrings.github.io/python/usage/configuration/docstrings/#show_docstring_examples
            show_docstring_examples: true
            # https://mkdocstrings.github.io/python/usage/configuration/docstrings/#show_docstring_other_parameters
            show_docstring_other_parameters: true
            # https://mkdocstrings.github.io/python/usage/configuration/docstrings/#show_docstring_parameters
            show_docstring_parameters: true
            # https://mkdocstrings.github.io/python/usage/configuration/docstrings/#show_docstring_raises
            show_docstring_raises: true
            # https://mkdocstrings.github.io/python/usage/configuration/docstrings/#show_docstring_receives
            show_docstring_receives: true
            # https://mkdocstrings.github.io/python/usage/configuration/docstrings/#show_docstring_returns
            show_docstring_returns: true
            # https://mkdocstrings.github.io/python/usage/configuration/docstrings/#show_docstring_warns
            show_docstring_warns: true
            # https://mkdocstrings.github.io/python/usage/configuration/docstrings/#show_docstring_yields
            show_docstring_yields: true

            ### Signatures

            # https://mkdocstrings.github.io/python/usage/configuration/signatures/#annotations_path
            annotations_path: brief
            # https://mkdocstrings.github.io/python/usage/configuration/signatures/#line_length
            line_length: 80
            # https://mkdocstrings.github.io/python/usage/configuration/signatures/#show_signature
            show_signature: true
            # https://mkdocstrings.github.io/python/usage/configuration/signatures/#show_signature_annotations
            show_signature_annotations: true
            # https://mkdocstrings.github.io/python/usage/configuration/signatures/#separate_signature
            separate_signature: false
            # https://mkdocstrings.github.io/python/usage/configuration/signatures/#show_overloads
            show_overloads: true
            # https://mkdocstrings.github.io/python/usage/configuration/signatures/#unwrap_annotated
            unwrap_annotated: false
  - api-autonav:
      modules:
        - ../tux
      nav_section_title: Tux Reference
      api_root_uri: reference
      exclude_private: false
      on_implicit_namespace_packge: raise
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#revisioning
# - git-revision-date-localized:
#     enable_creation_date: false
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-contributors
# - git-committers:
#     repository: allthingslinux/tux
#     branch: main
#
### MARKDOWN EXTENSIONS
#
markdown_extensions:
  - attr_list
  # https://github.com/mkdocs/mkdocs-click
  - mkdocs-click:
  # https://mkdocstrings.github.io/usage/theming/#syntax-highlighting
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
      anchor_linenums: true
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  # - pymdownx.snippets
  - admonition
  - pymdownx.details
  - footnotes
  - md_in_html
  - def_list
  - tables
#
### NAVIGATION
#
nav:
  - Home: index.md
  - Development:
      - Contributing: dev/contributing.md
      - Local Development: dev/local_development.md
      - Docker Development: dev/docker_development.md
      - Database: dev/database.md
      - Database Patterns: dev/database_patterns.md
      - Permissions: dev/permissions.md
  - CLI Reference: dev/cli/index.md
