name: 'Type Checking'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pyright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: 'poetry'

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install

      - name: Add Poetry environment to PATH
        run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

      - name: Run Pyright
        uses: jakebailey/pyright-action@v2
        with:
          version: "PATH"
          working-directory: "tux"
          python-platform: "Linux"
          python-version: "3.12"
          annotate: "all"