name: "Static Type Checking"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pyright:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "poetry"
          cache-dependency-path: |
            poetry.lock
            pyproject.toml

      - name: Cache Prisma Client
        uses: actions/cache@v4
        with:
          path: |
            .venv/lib/python*/site-packages/prisma
            .venv/lib/python*/site-packages/prisma_client_py*
          key: prisma-${{ runner.os }}-${{ hashFiles('prisma/schema.prisma') }}
          restore-keys: |
            prisma-${{ runner.os }}-

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - name: Install minimal dependencies (types only)
        run: |
          poetry install --only=main,types --no-interaction --no-ansi

      - name: Add Poetry venv to PATH
        run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

      - name: Generate Prisma Client (cached)
        run: |
          if [ ! -d .venv/lib/python*/site-packages/prisma ]; then
            poetry run prisma generate
          else
            echo "Prisma client found in cache, skipping generation"
          fi

      - name: Run Pyright
        uses: jakebailey/pyright-action@v2
        with:
          annotate: "errors"  # Only annotate errors, not warnings
